### ISSUE TITLE
installation failed, problems on p

### ISSUE THREAD

**Issue by filippodb** [YunoHost-Apps/reel2bits_ynh#34]
sadly I couldn't manage to install reel2bits with yunohost, this is the error messages on installation:

`Could not install reel2bits: An error occurred inside the app installation script
KeyError: 'HOME'
raise KeyError(key)
File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
PATH_HOME = os.environ.get('PYTHONZ_HOME') or os.path.join(os.environ['HOME'], '.pythonz')
File "/var/www/reel2bits/.pythonz/pythonz/define.py", line 33, in
from pythonz.define import PATH_HOME_ETC, PATH_PYTHONS
File "/var/www/reel2bits/.pythonz/pythonz/__init__.py", line 8, in
from pythonz.installer import install_pythonz
File "/var/www/reel2bits/.pythonz/pythonz_install.py", line 32, in
Traceback (most recent call last):
Installing Python 3.7.5...`

this is the log file:

`2020-05-05 03:40:43,909: DEBUG - ++ find /var/cache/yunohost/from_file/reel2bits_ynh-0fc25106736e824bd984b26f0c2146a6685904e0/scripts/../sources/patches/ -type f -name 'pythonz-*.patch'
2020-05-05 03:40:43,910: WARNING - Traceback (most recent call last):
2020-05-05 03:40:43,911: DEBUG - + ((  0 > 0  ))
2020-05-05 03:40:43,911: WARNING -   File "/var/www/reel2bits/.pythonz/pythonz_install.py", line 32, in <module>
2020-05-05 03:40:43,911: DEBUG - + test -e /var/cache/yunohost/from_file/reel2bits_ynh-0fc25106736e824bd984b26f0c2146a6685904e0/scripts/../sources/extra_files/pythonz
2020-05-05 03:40:43,912: WARNING -     from pythonz.installer import install_pythonz
2020-05-05 03:40:43,912: DEBUG - + export PYTHONZ_ROOT=/var/www/reel2bits/.pythonz
2020-05-05 03:40:43,912: WARNING -   File "/var/www/reel2bits/.pythonz/pythonz/__init__.py", line 8, in <module>
2020-05-05 03:40:43,913: DEBUG - + PYTHONZ_ROOT=/var/www/reel2bits/.pythonz
2020-05-05 03:40:43,913: WARNING -     from pythonz.define import PATH_HOME_ETC, PATH_PYTHONS
2020-05-05 03:40:43,913: DEBUG - + python /var/www/reel2bits/.pythonz/pythonz_install.py
2020-05-05 03:40:43,914: WARNING -   File "/var/www/reel2bits/.pythonz/pythonz/define.py", line 33, in <module>
2020-05-05 03:40:43,914: DEBUG - + ynh_exit_properly
2020-05-05 03:40:43,914: WARNING -     PATH_HOME = os.environ.get('PYTHONZ_HOME') or os.path.join(os.environ['HOME'], '.pythonz')
2020-05-05 03:40:43,915: DEBUG - + local exit_code=1
2020-05-05 03:40:43,915: WARNING -   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
2020-05-05 03:40:43,915: DEBUG - + '[' 1 -eq 0 ']'
2020-05-05 03:40:43,916: WARNING -     raise KeyError(key)
2020-05-05 03:40:43,916: DEBUG - + trap '' EXIT
2020-05-05 03:40:43,917: WARNING - KeyError: 'HOME'
2020-05-05 03:40:43,917: DEBUG - + set +eu
2020-05-05 03:40:43,917: DEBUG - + sleep 0.5
2020-05-05 03:40:44,420: DEBUG - + type -t ynh_clean_setup
2020-05-05 03:40:44,420: WARNING - 
2020-05-05 03:40:44,421: DEBUG - + ynh_clean_setup
2020-05-05 03:40:44,421: DEBUG - + ynh_clean_check_starting
2020-05-05 03:40:44,422: DEBUG - + '[' -n '' ']'
2020-05-05 03:40:44,422: DEBUG - + '[' -n '' ']'
2020-05-05 03:40:44,422: DEBUG - + ynh_die
2020-05-05 03:40:44,422: DEBUG - + local legacy_args=mc
2020-05-05 03:40:44,423: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2020-05-05 03:40:44,423: DEBUG - + declare -Ar args_array
2020-05-05 03:40:44,423: DEBUG - + local message
2020-05-05 03:40:44,424: DEBUG - + local ret_code
2020-05-05 03:40:44,424: DEBUG - + ynh_handle_getopts_args
2020-05-05 03:40:44,424: DEBUG - + set +x
2020-05-05 03:40:44,424: DEBUG - + echo ''
2020-05-05 03:40:44,424: DEBUG - + exit 1
2020-05-05 03:40:44,536: ERROR - Could not install reel2bits: An error occurred inside the app installation script`

**Comment by yalh76** [comment]
Have you tried to install it from the command line ?

**Comment by stemy2** [comment]
It failed for me too.

https://paste.yunohost.org/raw/egisikepif

**Comment by filippodb** [comment]
> Have you tried to install it from the command line ?

 I didn't tried from command line, honestly I use yunohost because it saves me from using command line :p
